// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-api-endpoint'
  | 'pref-api-key'
  | 'pref-api-model'
  | 'pref-backend'
  | 'pref-backend-kind'
  | 'pref-codex-effort'
  | 'pref-codex-model'
  | 'pref-codex-path'
  | 'pref-context-note'
  | 'pref-enable-auto'
  | 'pref-source-language'
  | 'pref-target-language'
  | 'pref-temperature'
  | 'pref-title'
  | 'pref-translation'
  | 'readerpopup-translate-label'
  | 'service-errorPrefix'
  | 'service-paper-context'
  | 'sidebar-no-attachment'
  | 'sidebar-preferences'
  | 'sidebar-source-placeholder'
  | 'sidebar-title'
  | 'sidebar-tooltip'
  | 'status-translating';
