// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enableAuto": boolean;
      "translateSource": string;
      "sourceLanguage": string;
      "targetLanguage": string;
      "enableAutoDetectLanguage": boolean;
      "fontSize": string;
      "lineHeight": string;
      "paper.backend": string;
      "paper.codexPath": string;
      "paper.codexModel": string;
      "paper.codexEffort": string;
      "paper.apiEndpoint": string;
      "paper.apiModel": string;
      "paper.temperature": string;
    };
  }
}
